apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ./infra/nginx/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 30s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    controller:
      service:
        type: NodePort
